site_name: VALRO Documentations
site_url: https://valkariaro.com
theme:
  name: material

  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.sections
   # - navigation.expand
    - toc.follow
    - content.tabs.link
   # - navigation.indexes
  
nav:
  - ValRO Guides:
    - ğŸ‘‹ Welcome To Valkaria : index.md
    - â„¹ï¸ Server Info: server-info.md
    - ğŸš© Getting Started: getting-started.md
  - Server features:
    - âš¡ï¸ Random Options: random-option.md
    - ğŸ’¸ Adjusted Price: adjusted-price.md
    - ğŸƒ Card Trader: card-trader.md
    - ğŸª™ Coin System: coin-system.md
    - ğŸ¦œ Cute Pets: cute-pet.md
    - ğŸ“œ Daily Quests: daily-quest.md
    - ğŸ©¹ Healer : healer.md
    - ğŸ¯ Hunting Missions: hunting-mission.md
    - ğŸ’ª MVP Features: mvp-features.md
    - ğŸŒ€ Warper System: warper-quest.md
    - ğŸ‘¹ Headgear Quest : headgear-quest.md
  - Custom Features:
    - ğŸ‰ Stats Discipline: stat-discipline.md
    - ğŸ§± Endless Cellar: endless-cellar.md
    - ğŸƒ Halloween Event: halloween.md
    - ğŸ§¸ Horror Toy Factory: horrortoyfactory.md
    - ğŸ¤– Mechromatrix: mecho.md
    - âšœï¸ King of Emperium: koe.md
  - Economy Guides:
    - ğŸ“ˆ Marketplace: marketplace.md
    - ğŸ” Mystery Market: mysterymarket.md
    - ğŸ’° Vendor: vendor.md
  - Troubleshooting:
    - ğŸ“• Rules: rules.md 
    - ğŸ› ï¸ Common Issues: troubleshoot.md
    - ğŸ’¡ Support Us: supportus.md
  
markdown_extensions:
  - neoteroi.timeline
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
plugins:
   - glightbox

extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css
  - stylesheets/neoteroi-timeline.css
  - stylesheets/neoteroi-mkdocs.min.css
